/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MethodRouteImport } from './routes/method'
import { Route as LicensingRouteImport } from './routes/licensing'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as FoundriesRouteImport } from './routes/foundries'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoundriesSlugRouteImport } from './routes/foundries.$slug'

const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensingRoute = LicensingRouteImport.update({
  id: '/licensing',
  path: '/licensing',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundriesRoute = FoundriesRouteImport.update({
  id: '/foundries',
  path: '/foundries',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundriesSlugRoute = FoundriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FoundriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/foundries': typeof FoundriesRouteWithChildren
  '/library': typeof LibraryRoute
  '/licensing': typeof LicensingRoute
  '/method': typeof MethodRoute
  '/foundries/$slug': typeof FoundriesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/foundries': typeof FoundriesRouteWithChildren
  '/library': typeof LibraryRoute
  '/licensing': typeof LicensingRoute
  '/method': typeof MethodRoute
  '/foundries/$slug': typeof FoundriesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/foundries': typeof FoundriesRouteWithChildren
  '/library': typeof LibraryRoute
  '/licensing': typeof LicensingRoute
  '/method': typeof MethodRoute
  '/foundries/$slug': typeof FoundriesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/foundries'
    | '/library'
    | '/licensing'
    | '/method'
    | '/foundries/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/foundries'
    | '/library'
    | '/licensing'
    | '/method'
    | '/foundries/$slug'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/foundries'
    | '/library'
    | '/licensing'
    | '/method'
    | '/foundries/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  FoundriesRoute: typeof FoundriesRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  LicensingRoute: typeof LicensingRoute
  MethodRoute: typeof MethodRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licensing': {
      id: '/licensing'
      path: '/licensing'
      fullPath: '/licensing'
      preLoaderRoute: typeof LicensingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundries': {
      id: '/foundries'
      path: '/foundries'
      fullPath: '/foundries'
      preLoaderRoute: typeof FoundriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundries/$slug': {
      id: '/foundries/$slug'
      path: '/$slug'
      fullPath: '/foundries/$slug'
      preLoaderRoute: typeof FoundriesSlugRouteImport
      parentRoute: typeof FoundriesRoute
    }
  }
}

interface FoundriesRouteChildren {
  FoundriesSlugRoute: typeof FoundriesSlugRoute
}

const FoundriesRouteChildren: FoundriesRouteChildren = {
  FoundriesSlugRoute: FoundriesSlugRoute,
}

const FoundriesRouteWithChildren = FoundriesRoute._addFileChildren(
  FoundriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  FoundriesRoute: FoundriesRouteWithChildren,
  LibraryRoute: LibraryRoute,
  LicensingRoute: LicensingRoute,
  MethodRoute: MethodRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
